fix: use separate dev and prod Azure connection strings for the different deployment targets

diff --git a/src/generator/templates/.github/workflows/pr-approved.yml b/src/generator/templates/.github/workflows/pr-approved.yml
--- a/src/generator/templates/.github/workflows/pr-approved.yml
+++ b/src/generator/templates/.github/workflows/pr-approved.yml
@@ -25,13 +25,20 @@ jobs:
         run: |
           echo "::error::PRs from forks are not supported (Github security issue).%0APRs should be from a branch in the same repo, created by a Contributor."
           exit 1
-      - name: check azure connection string
-        if: env.AZURE_CONNECTION_STRING == null
+      - name: check prod azure connection string
+        if: env.AZURE_PROD_CONNECTION_STRING == null
         run: |
-          echo "::error::Please set the Azure Blob Storage connection string as AZURE_CONNECTION_STRING in Github Secrets"
+          echo "::error::Please set the Azure Blob Storage connection string as AZURE_PROD_CONNECTION_STRING in Github Secrets"
           exit 1
         env:
-          AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
+          AZURE_PROD_CONNECTION_STRING: ${{ secrets.AZURE_PROD_CONNECTION_STRING }}
+      - name: check dev azure connection string
+        if: env.AZURE_DEV_CONNECTION_STRING == null
+        run: |
+          echo "::error::Please set the Azure Blob Storage connection string as AZURE_DEV_CONNECTION_STRING in Github Secrets"
+          exit 1
+        env:
+          AZURE_DEV_CONNECTION_STRING: ${{ secrets.AZURE_DEV_CONNECTION_STRING }}
 
   echo-state:
     needs: [set-state]
@@ -76,6 +83,8 @@ jobs:
         run: |
           npm install
           npm run build
+          mkdir $GITHUB_WORKSPACE/dist
+          mv $GITHUB_WORKSPACE/public $GITHUB_WORKSPACE/dist/$PATH_PREFIX
         env:
           PREFIX_PATHS: true # equivalent to --prefix-paths flag for 'gatsby build'
           PATH_PREFIX: ${{ github.event.repository.name }}
@@ -85,6 +94,12 @@ jobs:
           REPO_OWNER: ${{ github.event.repository.owner.login }}
           REPO_NAME: ${{ github.event.repository.name }}
           REPO_BRANCH: ${{ needs.set-state.outputs.branch_short_ref }}
+      - name: Deploy
+        uses: tibor19/static-website-deploy@v1
+        with:
+          enabled-static-website: 'true'
+          folder: 'dist'
+          connection-string: ${{ secrets.AZURE_DEV_CONNECTION_STRING }}
 
   post-build-dev:
     needs: [build-dev]
@@ -150,7 +165,7 @@ jobs:
         with:
           enabled-static-website: 'true'
           folder: 'dist'
-          connection-string: ${{ secrets.AZURE_CONNECTION_STRING }}
+          connection-string: ${{ secrets.AZURE_PROD_CONNECTION_STRING }}
 
   post-build-production:
     needs: [build-production]
